kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: "dev-lab-cluster"
nodes:
- role: control-plane
  image: "kindest/node:v1.32.0"
- role: worker
  image: "kindest/node:v1.32.0"
- role: worker
  image: "kindest/node:v1.32.0"
  #Optional: labels
  labels:
    role: app
- role: worker
  image: "kindest/node:v1.32.0"
  labels:
    role: ingress
    env: dev
  #Optional: extraPortMappings
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 5432
    hostPort: 5432
    protocol: TCP
  - containerPort: 9092
    hostPort: 9092
    protocol: TCP
  - containerPort: 9093
    hostPort: 9093
    protocol: TCP
  - containerPort: 9094
    hostPort: 9094
    protocol: TCP
  - containerPort: 3306
    hostPort: 3306
    protocol: TCP
  - containerPort: 6379
    hostPort: 6379
    protocol: TCP
  #Optional: kubeadmConfigPatches
  # Allows you to patch the kubeadm configuration for advanced settings. 
  # Example below sets a taint (role=ingress:NoSchedule) on the ingress node, so only pods that tolerate this taint can be scheduled there.
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        register-with-taints: "role=ingress:NoSchedule"