name: Build and Save Container Image with Podman

on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  IMAGE_NAME: kind-build
  IMAGE_TAG: ${{ github.sha }}
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build container image with Podman
      run: |
        podman build \
          -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          -t ${{ env.IMAGE_NAME }}:latest \
          -f ${{ env.DOCKERFILE_PATH }} \
          .

    - name: Save container image as archive
      run: |
        podman save \
          -o /tmp/${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}.tar \
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
        path: /tmp/${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}.tar
        retention-days: 30

    - name: Display build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Image Name:** ${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Image Tag:** ${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Tool:** Podman" >> $GITHUB_STEP_SUMMARY
        echo "- **Dockerfile:** ${{ env.DOCKERFILE_PATH }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Artifact Name:** ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Archive Location:** /tmp/${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}.tar" >> $GITHUB_STEP_SUMMARY